_target_: learner_wrapper.face_recognition.FaceRecognitionWrapper
backbone: ???
network_head: classifier
embedding_size: 512
mode: use_head
num_class: 100
device: cuda
example_input_shape: [1, 3, 112, 112]
