_target_: learner_wrapper.fall_detector.FallDetectorLearnerWrapper

pose_estimator:
  _target_: learner_wrapper.lightweight_openpose.LightweightOpenPoseLearnerWrapper
  device: cuda
  backbone: ???
  mobilenet_use_stride: False
  num_refinement_stages: 2
  half_precision: False

device: cuda
num_class: None
example_input_shape: [1, 3, 480, 640]
