_target_: learner_wrapper.lightweight_openpose.LightweightOpenPoseLearnerWrapper
device: cuda
backbone: ???
mobilenet_use_stride: True
num_refinement_stages: 0
half_precision: True
num_class: None
example_input_shape: [1, 3, 256, 256]