_target_: learner_wrapper.lightweight_openpose.LightweightOpenPoseLearnerWrapper
device: cuda
backbone: ???
mobilenet_use_stride: False
num_refinement_stages: 2
half_precision: False
num_class: None
example_input_shape: [1, 3, 256, 256]