_target_: learner_wrapper.progressive_spatio_temporal_bln.ProgressiveSpatioTemporalBLNWrapper
device: cuda
num_point: 312
num_class: 7
num_frames: 150
example_input_shape: [1, 2, 7, 312, 1]
dataset_name: afew